# reporter/txt_reporter.py
"""
WASP TXT Reporter — Phase 1
Generates a human-readable plain text report.
"""

import os
from datetime import datetime

from config import OUTPUT_DIR
from core.logger import get_logger
from core.models import ScanResult
from core.utils import sanitize_filename

log = get_logger(__name__)

SEVERITY_ICONS = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
    "INFO":     "🔵",
}


def generate(result: ScanResult) -> str:
    """
    Generate a TXT report from a ScanResult.
    Returns the path to the generated file.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = sanitize_filename(
        result.target.replace("http://", "").replace("https://", "")
    )
    filename = f"wasp_{safe_name}_{timestamp}.txt"
    filepath = os.path.join(OUTPUT_DIR, filename)

    lines = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "=" * 60,
        "  WASP — Web Application Security Probe v1.0",
        "  Scan Report",
        "=" * 60,
        f"  Target    : {result.target}",
        f"  Started   : {result.start_time}",
        f"  Finished  : {result.end_time}",
        "=" * 60,
        "",
    ]

    # ── Summary ───────────────────────────────────────────────────────────────
    lines += [
        "SUMMARY",
        "-" * 40,
        f"  URLs crawled    : {len(result.urls_crawled)}",
        f"  Vulnerabilities : {len(result.vulnerabilities)}",
        f"  Open ports      : {len(result.open_ports)}",
        f"  Errors          : {len(result.errors)}",
        "",
    ]

    # ── Vulnerabilities ───────────────────────────────────────────────────────
    lines += ["VULNERABILITIES", "-" * 40]

    if not result.vulnerabilities:
        lines.append("  No vulnerabilities found.")
    else:
        for i, v in enumerate(result.vulnerabilities, 1):
            icon = SEVERITY_ICONS.get(v.severity.value, "⚪")
            lines += [
                f"\n  [{i}] {icon} {v.vuln_type}",
                f"       Severity  : {v.severity.value}",
                f"       URL       : {v.url}",
                f"       Parameter : {v.parameter}",
                f"       Payload   : {v.payload}",
                f"       Evidence  : {v.evidence}",
                f"       Details   : {v.description}",
            ]
            if v.remediation:
                lines.append(f"       Fix       : {v.remediation}")

    lines.append("")

    # ── Open Ports ────────────────────────────────────────────────────────────
    lines += ["OPEN PORTS", "-" * 40]

    if not result.open_ports:
        lines.append("  No open ports found.")
    else:
        for p in result.open_ports:
            lines.append(f"  {p.port:<6} {p.state:<10} {p.service}")

    lines.append("")

    # ── Crawled URLs ──────────────────────────────────────────────────────────
    lines += ["CRAWLED URLs", "-" * 40]
    for url in result.urls_crawled:
        lines.append(f"  {url}")

    lines.append("")

    # ── Errors ────────────────────────────────────────────────────────────────
    if result.errors:
        lines += ["ERRORS", "-" * 40]
        for err in result.errors:
            lines.append(f"  [!] {err}")
        lines.append("")

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "=" * 60,
        "  Generated by WASP — For authorized testing only.",
        "=" * 60,
    ]

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log.info(f"TXT report saved: {filepath}")
    return filepath